import type { RequestDraft } from './types';

const quote = (text: string) => `'${text.replace(/'/g, `'"'"'`)}'`;
const octal = (binary: string) => Array.from(binary, c => `\\${c.charCodeAt(0).toString(8).padStart(3, '0')}`).join('');

/** Bash command; body goes through stdin so NUL and non-UTF-8 bytes survive. */
export function toCurl(request: RequestDraft): string {
  const connectionTokens = request.headers.filter(h => h.name.toLowerCase() === 'connection')
    .flatMap(h => h.value.toLowerCase().split(',').map(v => v.trim()));
  const omitted = new Set(['host', 'content-length', 'transfer-encoding', 'connection', 'proxy-connection',
    'proxy-authorization', 'keep-alive', 'te', 'trailer', 'upgrade', ...connectionTokens]);
  const headers = request.headers.filter(h => !omitted.has(h.name.toLowerCase()));
  const args = ['curl', '--globoff', '--path-as-is', '--request', quote(request.method), '--url', quote(request.url)];
  for (const header of headers) {
    // Captured HTTP/1 field values are mapped byte-for-byte to Latin-1 characters.
    const line = header.value ? `${header.name}: ${header.value}` : `${header.name};`;
    args.push('--header', /^[\x20-\x7e]*$/.test(line) ? quote(line) : `$'${octal(line)}'`);
  }
  const body = atob(request.bodyBase64);
  if (body) {
    if (!headers.some(h => h.name.toLowerCase() === 'content-type')) args.push('--header', quote('Content-Type:'));
    args.push('--data-binary', '@-');
  }
  const command = args.join(' ');
  return '# Bash / Git Bash. curl does not reproduce the selected ClientHello.\n'
    + '# Connection/framing headers are regenerated by curl.\n'
    + (body ? `printf '%b' ${quote(octal(body))} | ${command}` : command);
}
