import { writeClipboard } from './clipboard';
import { t } from './i18n';
import { CaptureScripts } from './ScriptsEditor';
import { useRef, useState } from 'react';
import { invoke } from './api';
import { decodeText, encodeText, type Flow } from './types';
import OrderedHeaders from './OrderedHeaders';
import ResponseBody from './ResponseBody';
import './interception.css';
type Rule = {disabled?:boolean;exclude?:boolean;group?:string;urlRegex?:boolean;urlContains:string;host:string;method:string;status:number|null;headerName:string;headerContains:string};
type Config = {request:boolean;response:boolean;scope:string;rules?:Rule[]};
type Item = {id:string;stage:string;flow:Flow};
export type InterceptSnapshot = {hits?:number[];config:Config;items:Item[]};
export default function Interception({snapshot,onUpdate}:{snapshot:InterceptSnapshot;onUpdate:(s:InterceptSnapshot)=>void}) {
 const [selected,setSelected]=useState(''); const [error,setError]=useState(''); const [saving,setSaving]=useState(false);
 const item=snapshot.items.find(i=>i.id===selected)??snapshot.items[0];
 async function configure(config:Config) { setSaving(true); try {await invoke('configure_interception',{config:{...config,scope:config.scope||'all'}});onUpdate(await invoke<InterceptSnapshot>('interception'));setError('');return true;} catch(e){setError(String(e));return false;} finally {setSaving(false);} }
 return <section className="interception-page"><div className="interception-controls"><strong>{t("拦截")}</strong>{(['request','response'] as const).map(stage=><label key={stage}><input disabled={saving} type="checkbox" checked={snapshot.config[stage]} onChange={e=>void configure({...snapshot.config,[stage]:e.target.checked})}/>{stage==='request'?t("请求发送前"):t("响应返回后")}</label>)}<select aria-label={t("拦截来源")} disabled={saving} value={snapshot.config.scope||'all'} onChange={e=>void configure({...snapshot.config,scope:e.target.value})}><option value="all">{t("全部来源")}</option><option value="capture">{t("抓包流量")}</option><option value="replay">{t("手动发送")}</option></select><span>{t("每阶段最多等待 120 秒；关闭开关将原样放行。")}</span></div>{error&&<p role="alert">{error}</p>}<Rules hits={snapshot.hits??[]} config={snapshot.config} save={configure} saving={saving}/><CaptureScripts/><div className="interception-workspace"><aside>{snapshot.items.map(i=><button key={i.id} className={item?.id===i.id?'active':''} onClick={()=>setSelected(i.id)}><strong>{i.stage==='request'?t("等待请求放行"):t("等待响应放行")} · {i.flow.source==='capture'?t("抓包"):t("手动")}</strong><span>{i.flow.request.method} {i.flow.request.url}</span></button>)}{!snapshot.items.length&&<p>{t("暂无等待项。开启拦截后，新的流量会在这里暂停。")}</p>}</aside>{item&&<Editor key={item.id} item={item} onDone={async()=>onUpdate(await invoke<InterceptSnapshot>('interception'))}/>}</div></section>;
}
function Rules({config,save,saving,hits}:{hits:number[];config:Config;save:(c:Config)=>Promise<boolean>;saving:boolean}) {
 const fileInput=useRef<HTMLInputElement>(null);const [fileError,setFileError]=useState('');
 const [draft,setDraft]=useState<Rule[]|null>(null); const rules=draft??config.rules??[];
 const update=(index:number,patch:Partial<Rule>)=>setDraft(rules.map((r,i)=>i===index?{...r,...patch}:r));
 function exportRules(){const url=URL.createObjectURL(new Blob([JSON.stringify({format:'http-capture-rules',version:1,rules},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='capture-rules.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 async function importRules(file:File){try{if(file.size>1024*1024)throw Error('Rules file exceeds 1 MiB');const value=JSON.parse(await file.text());if(value.format!=='http-capture-rules'||value.version!==1||!Array.isArray(value.rules)||value.rules.length>32)throw Error('Invalid rules file');for(const r of value.rules){if(!r||!['urlContains','host','method','headerName','headerContains'].every(k=>typeof r[k]==='string')||!['disabled','exclude','urlRegex'].every(k=>r[k]===undefined||typeof r[k]==='boolean')||(r.group!==undefined&&typeof r.group!=='string')||(r.status!==null&&(!Number.isInteger(r.status)||r.status<100||r.status>599)))throw Error('Invalid rule');}setDraft(value.rules);setFileError('');}catch(e){setFileError(String(e));}}
 return <details open className="interception-rules"><summary>{t("匹配规则 · 已应用")}{config.rules?.length??0} {t("条")}</summary><p>{t("只拦截匹配的流量；没有规则时全部通过。同一行条件须同时满足，多行满足任意一行即可。状态码条件只匹配响应阶段。正则匹配完整 URL 中的任意位置；用 ^ 和 $ 限定边界，(?i) 忽略大小写，不需要 /…/ 分隔符。不支持环视或反向引用。")}</p>{rules.map((r,i)=><div className="interception-controls" key={i}>
 <label><input type="checkbox" checked={!r.disabled} onChange={e=>update(i,{disabled:!e.target.checked})}/>{t('启用')}</label><label><input type="checkbox" checked={!!r.exclude} onChange={e=>update(i,{exclude:e.target.checked})}/>{t('排除')}</label><input aria-label={t('规则分组')} placeholder={t('规则分组')} value={r.group??''} onChange={e=>update(i,{group:e.target.value})}/><small>{t('断点命中')} {hits[i]??0}</small>
 <select aria-label={t("URL 匹配方式 {v0}", { v0: i+1 })} value={r.urlRegex?'regex':'contains'} onChange={e=>update(i,{urlRegex:e.target.value==='regex'})}><option value="contains">{t("URL 包含")}</option><option value="regex">{t("URL 正则表达式")}</option></select><input aria-label={t("URL 条件 {v0}", { v0: i+1 })} placeholder={r.urlRegex?t("如 ^https://httpbin\\.org/.*"):t("URL 包含（区分大小写）")} value={r.urlContains} onChange={e=>update(i,{urlContains:e.target.value})}/>
 <input aria-label={t("域名 {v0}", { v0: i+1 })} placeholder={t("域名精确匹配，如 httpbin.org")} value={r.host} onChange={e=>update(i,{host:e.target.value})}/>
 <input aria-label={t("方法 {v0}", { v0: i+1 })} placeholder={t("方法，如 POST")} value={r.method} onChange={e=>update(i,{method:e.target.value})}/>
 <input aria-label={t("状态码 {v0}", { v0: i+1 })} type="number" min="100" max="599" placeholder={t("响应状态码")} value={r.status??''} onChange={e=>update(i,{status:e.target.value?Number(e.target.value):null})}/>
 <input aria-label={t("请求头名称 {v0}", { v0: i+1 })} placeholder={t("请求头名称")} value={r.headerName} onChange={e=>update(i,{headerName:e.target.value})}/>
 <input aria-label={t("请求头值包含 {v0}", { v0: i+1 })} placeholder={t("请求头值包含（空为存在即可）")} value={r.headerContains} onChange={e=>update(i,{headerContains:e.target.value})}/>
 <button onClick={()=>setDraft(rules.filter((_,n)=>n!==i))}>{t("删除规则")}{i+1}</button></div>)}
 <div className="interception-controls"><button onClick={exportRules}>{t('导出规则')}</button><button disabled={saving} onClick={()=>fileInput.current?.click()}>{t('导入规则')}</button><input hidden type="file" accept=".json" ref={fileInput} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void importRules(file);}}/>{fileError&&<span role="alert">{fileError}</span>}</div><p>{t('排除规则优先；分组仅用于标记。命中次数为本次配置的断点暂停次数，修改配置后归零。')}</p><div className="interception-controls"><button disabled={rules.length>=32} onClick={()=>setDraft([...rules,{urlContains:'',host:'',method:'',status:null,headerName:'',headerContains:''}])}>{t("添加规则")}</button><button disabled={saving||draft===null} onClick={()=>void save({...config,rules}).then(ok=>{if(ok)setDraft(null);})}>{t("应用规则")}</button><button disabled={draft===null} onClick={()=>setDraft(null)}>{t("取消修改")}</button>{draft!==null&&<span>{t("有未应用的修改")}</span>}</div></details>;
}
function Editor({item,onDone}:{item:Item;onDone:()=>Promise<void>}) {
 const [request,setRequest]=useState(item.flow.request);
 const [response,setResponse]=useState<NonNullable<Flow['response']>>(item.flow.response??{status:200,version:'HTTP/1.1',headers:[{name:'Content-Type',value:'text/plain; charset=utf-8'}],bodyBase64:''});
 const [replace,setReplace]=useState(false); const [base64,setBase64]=useState(true); const [preview,setPreview]=useState(false); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const editingResponse=item.stage==='response'||replace; const message=editingResponse?response:request;
 const setHeaders=(headers:typeof request.headers)=>editingResponse?setResponse({...response,headers}):setRequest({...request,headers});
 function setBody(value:string) {const bodyBase64=base64?value:encodeText(value); if(editingResponse){setResponse({...response,bodyBase64,headers:response.headers.filter(h=>!['content-encoding','content-length','transfer-encoding'].includes(h.name.toLowerCase()))});}else setRequest({...request,bodyBase64});}
 async function resolve(action:string) {setBusy(true);try {await invoke('resolve_interception',{decision:{id:item.id,action,request:action==='modify'&&!editingResponse?request:null,response:action==='replace'||action==='modify'&&editingResponse?response:null}});await onDone();}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <div className="interception-editor"><div className="interception-controls"><strong>{editingResponse?t("响应编辑"):t("请求编辑")}</strong>{item.stage==='request'&&<label><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>{t("直接替换响应（不发送请求）")}</label>}<button onClick={()=>{setRequest(item.flow.request);setResponse(item.flow.response??{status:200,version:'HTTP/1.1',headers:[],bodyBase64:''});}}>{t("恢复原始内容")}</button></div>{editingResponse?<label>{t("状态码")}<input aria-label={t("拦截响应状态码")} type="number" value={response.status} onChange={e=>setResponse({...response,status:Number(e.target.value)})}/></label>:<div className="request-bar"><input aria-label={t("拦截请求方法")} value={request.method} onChange={e=>setRequest({...request,method:e.target.value})}/><input aria-label={t("拦截请求 URL")} value={request.url} onChange={e=>setRequest({...request,url:e.target.value})}/></div>}<OrderedHeaders headers={message.headers} onChange={setHeaders}/><div className="interception-controls"><span>{t("正文")}</span><select aria-label={t("拦截正文编码")} value={base64?'base64':'text'} onChange={e=>setBase64(e.target.value==='base64')}><option value="base64">{t("Base64（原始字节）")}</option><option value="text">UTF-8</option></select>{editingResponse&&<button onClick={()=>setPreview(!preview)}>{preview?t("编辑"):t("格式化 / 预览")}</button>}</div>{editingResponse&&<small>{t("压缩响应请先替换为解压后的正文；修改正文会移除原压缩及长度头。")}</small>}{preview&&editingResponse?<ResponseBody body={response.bodyBase64} headers={response.headers} onCopy={v=>void writeClipboard(v).catch(e=>setError(String(e)))}/>:<textarea aria-label={t("拦截正文")} value={base64?message.bodyBase64:decodeText(message.bodyBase64)} onChange={e=>setBody(e.target.value)}/>}<details><summary>{t("原始内容（保留备查）")}</summary><pre>{JSON.stringify(item.stage==='request'?item.flow.request:item.flow.response,null,2)}</pre></details>{error&&<p role="alert">{error}</p>}<div className="interception-controls"><button disabled={busy} onClick={()=>void resolve('continue')}>{t("原样放行")}</button><button disabled={busy} onClick={()=>void resolve(replace?'replace':'modify')}>{replace?t("返回自定义响应"):t("修改后放行")}</button><button disabled={busy} onClick={()=>void resolve('abort')}>{t("终止")}</button></div></div>;
}
