import { t } from './i18n';
import { useEffect, useState } from 'react';
import { invoke } from './api';
import type { UpstreamProfile, UpstreamStatus } from './types';
export default function UpstreamSettings({current,connected,onSaved}:{current?:UpstreamStatus;connected:boolean;onSaved:()=>Promise<void>}) {
 const [profiles,setProfiles]=useState<UpstreamProfile[]>([]);const [editing,setEditing]=useState(false);const [id,setId]=useState<string|null>(null);
 const [remember,setRemember]=useState(false);const [name,setName]=useState('');const [url,setUrl]=useState('http://127.0.0.1:7890');const [auth,setAuth]=useState(false);const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{let live=true;invoke<UpstreamProfile[]>('upstream_profiles').then(p=>{if(live)setProfiles(p);}).catch(e=>{if(live)setMessage(String(e));});return()=>{live=false;};},[]);
 async function refresh(){setProfiles(await invoke<UpstreamProfile[]>('upstream_profiles'));await onSaved();}
 function edit(p?:UpstreamProfile){setId(p?.id??null);setName(p?.name??'');setUrl(p?.url??'http://127.0.0.1:7890');setAuth(p?.authEnabled??false);setUsername(p?.username??'');setPassword('');setRemember(p?.rememberPassword??false);setEditing(true);setMessage('');}
 async function action(work:()=>Promise<void>,success:string){setBusy(true);setMessage('');try{await work();await refresh();setMessage(success);}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 const original=profiles.find(p=>p.id===id);
 async function save(){await action(async()=>{await invoke('save_upstream_profile',{input:{id,name,rememberPassword:auth&&remember,config:{enabled:true,url,authEnabled:auth,username,password:auth&&original?.authEnabled&&!original.needsPassword&&!password?null:password}}});setPassword('');setEditing(false);},id!==null&&id===current?.profileId?t("已保存，当前代理配置已更新，下一条请求生效。"):t("已保存到代理列表，点击使用即可切换。"));}
 return <fieldset className="upstream-settings" disabled={!connected||busy}><legend>{t("上游代理列表")}</legend>
 <label>{t("当前转发方式")}<select aria-label={t("切换上游代理")} value={current?.enabled?(current.profileId??'temporary'):''} onChange={e=>{const selected=e.target.value;void action(async()=>{await invoke('select_upstream_profile',{id:selected||null});},selected?t("已切换上游代理，下一条捕获请求生效。"):t("已切换为直连。"));}}><option value="">{t("直连（不使用上游代理）")}</option>{current?.enabled&&!current.profileId&&<option value="temporary" disabled>{t("临时代理：")}{current.url}</option>}{profiles.map(p=><option key={p.id} value={p.id} disabled={p.needsPassword}>{p.name} · {p.url}{p.needsPassword?t(" · 需补填密码"):''}</option>)}</select></label>
 <div className="upstream-profile-list">{profiles.map(p=><div className="upstream-profile" key={p.id}><div><strong>{p.name}{current?.profileId===p.id?t(" · 当前使用"):''}</strong><small>{p.url}{p.needsPassword?t(" · 需补填密码"):p.rememberPassword?t(" · 已记住密码"):''}</small>{p.credentialError&&<small role="alert">{p.credentialError}</small>}</div><button disabled={p.needsPassword||current?.profileId===p.id} onClick={()=>void action(async()=>{await invoke('select_upstream_profile',{id:p.id});},t("已切换至 {v0}。", { v0: p.name }))}>{t("使用")}</button><button disabled={p.needsPassword} title="example.com:443" onClick={async()=>{setBusy(true);try{const ms=await invoke<number>('test_upstream',{id:p.id});setMessage(`${t('代理隧道已连通')} example.com:443 · ${ms} ms`);}catch(e){setMessage(String(e));}finally{setBusy(false);}}}>{t('测试隧道')}</button><button onClick={()=>edit(p)}>{t("编辑")}</button><button disabled={current?.profileId===p.id} title={current?.profileId===p.id?t("先切换到其他代理或直连"):t("删除此代理配置")} onClick={()=>void action(async()=>{await invoke('delete_upstream_profile',{id:p.id});if(id===p.id)setEditing(false);},t("代理已删除。"))}>{t("删除")}</button></div>)}</div>
 {!profiles.length&&<p>{t("暂无保存的代理，可按业务创建配置。")}</p>}<button className="button" onClick={()=>edit()}>{t("新增代理")}</button>
 {editing&&<div className="upstream-profile-editor"><label>{t("业务名称")}<input aria-label={t("代理名称")} value={name} maxLength={80} placeholder={t("例如：支付测试环境")} onChange={e=>setName(e.target.value)}/></label><label>{t("代理地址")}<input aria-label={t("上游代理地址")} value={url} onChange={e=>setUrl(e.target.value)} placeholder={t("http://127.0.0.1:7890 或 socks5://127.0.0.1:1080")}/></label><label className="upstream-toggle"><input type="checkbox" checked={auth} onChange={e=>setAuth(e.target.checked)}/>{t("用户名 / 密码认证")}</label>{auth&&<div className="upstream-auth"><label>{t("用户名")}<input autoComplete="off" aria-label={t("上游代理用户名")} value={username} onChange={e=>setUsername(e.target.value)}/></label><label>{t("密码")}<input type="password" autoComplete="new-password" aria-label={t("上游代理密码")} value={password} placeholder={original?.authEnabled&&!original.needsPassword?t("留空保留密码（地址或用户名变化需重填）"):t("输入密码")} onChange={e=>setPassword(e.target.value)}/></label></div>}{auth&&<label className="upstream-toggle"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>{t("记住密码（系统凭据库）")}</label>}<button className="button" onClick={()=>void save()}>{t("保存代理")}</button><button onClick={()=>{setEditing(false);setPassword('');}}>{t("取消")}</button></div>}
 <p>{t("名称、地址及认证用户名保存到本地。勾选“记住密码”后，密码保存在系统凭据库；否则仅保留至服务退出。重启后默认直连。")}</p><p>{t("此处的当前转发方式用于抓包；手动请求可在自己的“设置”中选择列表里的代理。支持 HTTP 和 SOCKS5；失败不回退直连。HTTP/3 上游仅支持 SOCKS5 UDP，需代理支持 UDP 转发。")}</p>{message&&<p role="status">{message}</p>}</fieldset>;
}
